<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda [
<!ELEMENT agenda (persona)+>
<!ELEMENT persona (nombre, tlf, tw?)>
<!ATTLIST persona id ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tlf (#PCDATA)>
<!ELEMENT tw (#PCDATA)>
]>

<agenda>
<persona id="juan">
  <nombre>Juan Sanchez</nombre>
  <tlf>951345679</tlf>
</persona>

<persona id="ana">
  <nombre>Ana Diaz</nombre>
  <tlf>955837659</tlf>
  <tw>@anadiaz</tw>
</persona>
</agenda>