<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE etiqueta [
<!ELEMENT etiqueta (nombre, calle, ciudad?, pais, codigo)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT calle (#PCDATA)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT codigo (#PCDATA)>
]>

<etiqueta>
    <nombre>Pepe Garcia</nombre>
    <calle>C/Ronda3</calle>
    <pais>EspaÃ±a</pais>
    <codigo>18465</codigo>
</etiqueta>