<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE note [
<!ELEMENT note (to+,from,heading,(body|mensaje))>
<!ELEMENT to (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT mensaje (#PCDATA)>
]>
<note>
    <to>Mercedes</to>
    <to>Moises</to>
    <from>Jose</from>
    <heading>Recordatorio</heading>
    <mensaje>No olvides el cumpleaños de Andrés</mensaje>
</note>